title: "Stock Indicators"
tagline: "Send in historical price quotes and get back desired technical indicators.  Nothing more."

theme: jekyll-theme-cayman

exclude:
  [
    "wraps",
    "tests/indicators",
    "tests/external",
    "*.sln",
    "*.csproj",
    "*.cs",
    "*.xlsx",
    "*.xml",
    "*.yml",
    ".github",
    ".vscode"
  ]

include:
  [
  "docs", 
  "LICENSE",
  "wraps/**/*.md"
  ]

plugins:
  - jemoji

google_analytics: G-7602GXEZ0R
