# Ref: https://jekyllrb.com/docs/usage/
# Local dev: bundle exec jekyll serve --livereload

title: Stock Indicators for .NET
tagline: "Transform price quotes into trading insights."
repository: DaveSkender/Stock.Indicators
locale: en_US
baseurl: ""
url: "https://dotnet.stockindicators.dev"

# social media information
image:
  path: /assets/social-banner.png
  height: 640
  width: 1280

logo: /assets/icons/android-chrome-192x192.png

social:
  name: Dave Skender
  links:
    - https://twitter.com/daveskender
    - https://www.linkedin.com/in/skender
    - https://github.com/DaveSkender

author:
  name: Dave Skender
  twitter: daveskender
  url: https://www.linkedin.com/in/skender

twitter:
  username: daveskender
  card: summary

clarity: false

# site plugins and settings
plugins:
  - jekyll-github-metadata
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-last-modified-at
  - jekyll-redirect-from
  - jekyll-minifier

exclude:
  [
    "*.cs",
    "*.csproj",
    "*.json",
    "*.lock",
    "*.yml",
    "*.pptx",
    "*.sln",
    ".offline",
    "docs/README.md",
    "examples/Backtest",
    "examples/ConsoleApp",
    "GemFile",
    "node_modules",
    "vendor",
  ]

permalink: pretty

defaults:
  - scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "base"
      image: /assets/social-banner.png

# page collections
collections:
  indicators:
    output: true
    permalink: /:path
    sort_by: "title"
