# Ref: https://jekyllrb.com/docs/usage/
# Ref: https://github.com/pages-themes/cayman
# Local dev: bundle exec jekyll serve --livereload

title: Stock Indicators for .NET
tagline: "Transform price quotes into trading insights."
locale: en_US

# social media information
image:
  path: /assets/social-banner.png
  height: 640
  width: 1280

logo: /assets/icons/android-chrome-192x192.png

social:
  name: Dave Skender
  links:
    - https://twitter.com/daveskender
    - https://www.linkedin.com/in/skender
    - https://github.com/DaveSkender

author:
  name: Dave Skender
  twitter: daveskender

twitter:
  username: daveskender
  card: summary

# https://github.com/pages-themes/cayman
remote_theme: pages-themes/cayman@v0.2.0

# override built-in github url because it does not fetch in build tests
github:
  repository_url: https://github.com/DaveSkender/Stock.Indicators

ga_tag: G-7602GXEZ0R
clarity: false

# site plugins and settings
plugins:
  - jemoji
  - jekyll-remote-theme
  - jekyll-sitemap
  - jekyll-last-modified-at
  - jekyll-redirect-from

exclude: [
  "*.cs",
  "*.csproj",
  "*.json",
  "*.lock",
  "*.yml",
  "*.pptx",
  "*.sln",
  ".offline",
  "examples/Backtest",
  "examples/ConsoleApp",
  "GemFile",
  "node_modules",
  "vendor"
]

include: [
  "contributing.md",
  "guide.md",
  "indicators.html",
  "performance.md",
  "utilities.md"
]

permalink: pretty

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "base"
      image: /assets/social-banner.png
      description: Transform financial market prices into technical analysis insights with this best in class C# NuGet library.  Go further with chaining and custom indicators.

# page collections
collections:
  indicators:
    output: true
    permalink: /:path/
    sort_by: "title"
