# Ref: https://jekyllrb.com/docs/usage/
# Ref: https://github.com/pages-themes/cayman
# Local dev: bundle exec jekyll serve

title: "Stock Indicators for .NET"
tagline: "Send in historical price quotes and get back desired technical indicators.  Nothing more."

# override built-in github url because it does not fetch in build tests
github:
  repository_url: "https://github.com/DaveSkender/Stock.Indicators"

# https://github.com/pages-themes/cayman
remote_theme: pages-themes/cayman@v0.2.0

plugins:
  - jemoji
  - jekyll-remote-theme
  - jekyll-sitemap
  - jekyll-last-modified-at
  - jekyll-redirect-from

google_analytics: G-7602GXEZ0R

exclude: [
  "*.json",
  "*.lock",
  "*.yml",
  "*.pptx",
  ".offline",
  "contributing.md",
  "examples/Backtest",
  "examples/ConsoleApp",
  "examples/*.sln",
  "GemFile",
  "node_modules",
  "vendor"
]

include: [
  "guide.md",
  "indicators.html",
  "performance.md",
  "utilities.md"
]

permalink: pretty

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "base"

# page collections
collections:
  indicators:
    output: true
    permalink: /:path/
    sort_by: "title"
