name: Indicators

on:
  push:
    branches: ["main"]

  pull_request:
    branches: ["main"]

jobs:

  test:
    name: unit tests
    runs-on: ubuntu-latest

    steps:

      - name: Clean workspace
        run: |
          rm -rf ./test-indicators/* || true
          rm -rf ./test-indicators/.??* || true
          rm -rf ./NuGet/* || true
          rm -rf ./NuGet/.??* || true

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "8.x"
          dotnet-quality: "ga"

      - name: Compose version
        id: compose
        run: |
          COMPOSED_VERSION=${{ 'DEVTEST' }}
          echo "version=$COMPOSED_VERSION" >> "$GITHUB_OUTPUT"
          echo "COMPOSED_VERSION=$COMPOSED_VERSION" >> "$GITHUB_ENV"

      - name: Temporary
        uses: jacobtomlinson/gha-find-replace@v3
        with:
          include: "src/**/*.csproj"
          find: "<PackageReleaseNotes>https://github.com/DaveSkender/Stock.Indicators/releases</PackageReleaseNotes>"
          replace: "<PackageReleaseNotes>https://github.com/DaveSkender/Stock.Indicators/releases/tag/${{ steps.compose.outputs.version }}</PackageReleaseNotes>"
          regex: false

      - name: Build solution
        run: >
          dotnet build
          --configuration Release
          --property:ContinuousIntegrationBuild=true
          -warnAsError

      - name: Test indicators
        id: test-library
        env:
          ALPACA_KEY: ${{ secrets.ALPACA_KEY }}
          ALPACA_SECRET: ${{ secrets.ALPACA_SECRET }}
        run: >
          dotnet test tests/indicators/Tests.Indicators.csproj
          --configuration Release
          --no-build
          --verbosity normal
          --logger trx
          --collect:"XPlat Code Coverage"
          --results-directory ./test-indicators

      - name: Test other items
        id: test-other
        run: >
          dotnet test tests/other/Tests.Other.csproj
          --configuration Release
          --no-build
          --verbosity normal
          --logger trx
          --results-directory ./test-other

      - name: Post tests summary
        uses: bibipkins/dotnet-test-reporter@v1.3.3
        if: ${{ github.event_name == 'pull_request' && (success() || (failure() && (steps.test-library.conclusion == 'failure' || steps.test-other.conclusion == 'failure'))) }}
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          comment-title: ""
          results-path: ./test-indicators/**/*.trx
          coverage-path: ./test-indicators/**/coverage.cobertura.xml
          coverage-type: cobertura

      - name: Post coverage to Codacy
        uses: codacy/codacy-coverage-reporter-action@v1
        with:
          project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
          coverage-reports: ./test-indicators/**/coverage.cobertura.xml
          # or a comma-separated list for multiple reports
          # coverage-reports: <PATH_TO_REPORT>, <PATH_TO_REPORT>
