name: Lock closed threads
# https://github.com/marketplace/actions/lock-threads

on:
  schedule:
    - cron: "0 4 * * 0"
  workflow_dispatch:

permissions:
  issues: write
  pull-requests: write

concurrency:
  group: lock

jobs:
  lock:
    runs-on: ubuntu-slim
    timeout-minutes: 10

    steps:
      - uses: dessant/lock-threads@v6.0.0
        with:
          process-only: issues, prs
          issue-inactive-days: "90"
          pr-inactive-days: "30"
