name: test
on:
  pull_request:
    branches: [main]

jobs:
  test:
    name: a11y and URLs
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v2

      - name: Install Ruby
        uses: ruby/setup-ruby@v1
        with:
          working-directory: docs
          ruby-version: 2.7.0
          bundler-cache: true

      - name: Install GEMs
        working-directory: docs
        run: |
          pwd
          BUNDLE_GEMFILE="${{github.workspace}}/docs/GemFile" bundle install

      - name: Build site
        working-directory: docs
        run: BUNDLE_GEMFILE="${{github.workspace}}/docs/GemFile" bundle exec jekyll build

      - name: Serve site
        working-directory: docs
        run: BUNDLE_GEMFILE="${{github.workspace}}/docs/GemFile" bundle exec jekyll serve --detach

      - name: Test for broken URLs
        working-directory: docs
        run: |
          BUNDLE_GEMFILE="${{github.workspace}}/docs/GemFile" bundle exec htmlproofer \
            --http-status-ignore "403,999" \
            --url-swap "https\://daveskender.github.io/Stock.Indicators:http\://127.0.0.1:4000" \
            _site

      - name: Test accessibility
        working-directory: docs
        run: |
          npm i -g pa11y-ci
          pa11y-ci \
            --sitemap http://127.0.0.1:4000/sitemap.xml \
            --sitemap-exclude "/*.pdf"
